[tasks.deploy-web-testing]
description = 'Deploy testing version with a testing repository. | [--m <commit_message>]'
env = { REPO_NAME = 'DST-Helper-web-testing' }
run = '''
rm -rf build/web
git clone git@github.com:woin2ee/${REPO_NAME}.git build/web
flutter build web --base-href "/${REPO_NAME}/"
cd build/web
date >> date
git add .
git commit -m {{option(name="m")}}
git push
'''

[tasks.run-web-release]
description = 'Run for web server with given ip-address on release. | [ip_address]'
run = 'flutter run -d web-server --web-hostname {{arg()}} --web-port 8080 --release'