name: Deploy by tag

on:
  push:
    branches:
      - main

    # tags:
    #   - "*.*.*"

jobs:
  deploy_web_by_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Flutter action
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
      - run: flutter --version
      - name: Build for web release
        env:
          BASE_HREF: "/DST-Helper-web/"
        run: |
          flutter pub get
          dart run build_runner build
          flutter build web -t lib/app/entry_point/release/main.dart --base-href "${BASE_HREF}"
      - name: Copy `README.md` to the build dir
        run: cp README_web.md build/web/README.md
      - name: Move to build dir for web
        run: cd build/web
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "build/web"
          destination-github-username: "woin2ee"
          destination-repository-name: "DST-Helper-web"
          user-email: woin2ee@gmail.com
          target-branch: main
